[versions]
kotlin = "2.4.20"
ksp = "2.3.12"
room = "2.8.5"
kotlinpoet = "1.18.1"
junit5 = "5.10.2"
junitPlatform = "6.1.3"
compileTesting = "0.14.0"
agp = "8.11.1"
bcv = "0.18.2"
dokka = "2.2.0"
coroutines = "1.11.0"
robolectric = "4.17"
androidxTestCore = "1.7.0"
sqlite = "2.4.0"
junit4 = "4.13.2"

[libraries]
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx     = { module = "androidx.room:room-ktx",     version.ref = "room" }
room-common  = { module = "androidx.room:room-common",  version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite        = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

robolectric     = { module = "org.robolectric:robolectric",   version.ref = "robolectric" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }

ksp-api        = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet     = { module = "com.squareup:kotlinpoet",     version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit5      = { module = "org.junit.jupiter:junit-jupiter",  version.ref = "junit5" }
junit4      = { module = "junit:junit", version.ref = "junit4" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

kotlin-compile-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "compileTesting" }
kotlin-compile-testing-core = { module = "dev.zacsweers.kctfork:core", version.ref = "compileTesting" }

[plugins]
kotlin-jvm     = { id = "org.jetbrains.kotlin.jvm",     version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp            = { id = "com.google.devtools.ksp",      version.ref = "ksp" }
android-library = { id = "com.android.library",         version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
dokka          = { id = "org.jetbrains.dokka",           version.ref = "dokka" }
dokka-javadoc  = { id = "org.jetbrains.dokka-javadoc",   version.ref = "dokka" }
